### ISSUE TITLE
Home assistant Core 2023.3.2 - Inaccessible

### ISSUE THREAD

**Issue by thundrM** [thomasloven/hass-plejd#57]
Hi!

Updated my system to 2023.3.2 today and cant get my plejd lights to work again. worked perfectly before but now it just shows as "Inaccessible" i have tried to remove the integration and add it again and that works and i find all my lights but status is still "inaccessible" 
Is this just at my end or is it something that broke in the latest update?

**Comment by thomasloven** [comment]
I think you got some of those numbers mixed up. If not, I only support the latest version, which is 2024.2.4.
And there I cannot reproduce this problem.

**Comment by thundrM** [comment]
Sorry ofc I meant 2024.2.3, right after I wrote this I got notified about new update and I updated to 2024.2.4 but the problem still are still there. God to know its on my end if its working for you. will try to un and reinstall everything!

Thanks for your awesome work!

**Comment by thundrM** [comment]
[home-assistant_plejd_2024-02-27T07-52-06.007Z.log](https://github.com/thomasloven/hass-plejd/files/14416151/home-assistant_plejd_2024-02-27T07-52-06.007Z.log)

**Comment by thundrM** [comment]
Dont know what it was but i removed the bluetooth adapter and deleted the integration and configured it again and now it works! Weird problem as this happend immediately after I updated Home assistant. But now it works again so thanks for the support!

Thanks again for this amazing project!

**Comment by thundrM** [comment]
Dont know what it was but i removed the bluetooth adapter and deleted the integration and configured it again and now it works! Weird problem as this happend immediately after I updated Home assistant. But now it works again so thanks for the support!

Thanks again for this amazing project!
