### ISSUE TITLE
OUT-01 is not supported

### ISSUE THREAD

**Issue by bm500** [thomasloven/hass-plejd#58]
_OUT-01 is not supported, because they are unreleased, and I don't have access to any.
If you have an OUT-01 or any new device, please get in touch to help me get them supported._

First of all, thank you for a very good integration!
I'm reaching out to, if possible, help to get OUT-01 supported.

The integration founds the device and I can control temperature and brightness. I have made an automation to turn ligth on then sun goes down but by som reson the device sometimes don't respond.

Please let me know if I can be to some assistant!

[config_entry-plejd-aac7e4b63e67aaf4c4a30625da5a5458.json](https://github.com/thomasloven/hass-plejd/files/14423109/config_entry-plejd-aac7e4b63e67aaf4c4a30625da5a5458.json)

![Skärmbild 2024-02-27 175105](https://github.com/thomasloven/hass-plejd/assets/71224205/05a34a90-b28f-44fe-a804-0bf518de348f)

![Skärmbild 2024-02-27 174720](https://github.com/thomasloven/hass-plejd/assets/71224205/65c7c2ca-5018-425f-842c-7a374e69af99)

**Comment by thomasloven** [comment]
Thanks!
Since everything worked out of the box, the only thing I needed was the number 103 (from `-unknown- (103)`).
I'll try to have it recognize the model later today.

**Comment by thomasloven** [comment]
Should be named correctly in 0.11.0

**Comment by bm500** [comment]
Thank you! It's working 👍
