### ISSUE TITLE
DAL-01 brightness control

### ISSUE THREAD

**Issue by jesperrahmqvist** [thomasloven/hass-plejd#59]
Can you add support for brightness control for Plejd DAL-01 dimmers? The Plejd-Hassio integration has this.

**Comment by thomasloven** [comment]
Can you please send me your diagnotics data and tell me which lights don't work as expected? 
![image](https://github.com/thomasloven/hass-plejd/assets/1299821/92cef65c-de70-4139-bbf5-93007bf79873)

**Comment by jesperrahmqvist** [comment]
[config_entry-plejd-729f88234273f1d0e2ee2e0b8b96a195.json](https://github.com/thomasloven/hass-plejd/files/14470140/config_entry-plejd-729f88234273f1d0e2ee2e0b8b96a195.json)

Attached the diagnostics data. All DAL-01 do not get Brightness Sliders.

**Comment by jesperrahmqvist** [comment]
I see now that the names are different in the json file. I think the correct ones are:
Rail Play Room
Led list
Skena 3m
Led lighting
Led lister
Rail

**Comment by jesperrahmqvist** [comment]
This device id for example: C24E45D3E0A2 (the Skena 3m)

**Comment by thomasloven** [comment]
Thanks! It should work better now.

**Comment by jesperrahmqvist** [comment]
Thsnkyou 🙏🏻🤩 Works great!
