### ISSUE TITLE
Hidden switches don't show up

### ISSUE THREAD

**Issue by pierrei** [thomasloven/hass-plejd#64]
I just tried out the project and boy does it work well! Apart from one thing :D

I have a few switches (SPR-01) that are configured in the Plejd app to be hidden from the room they're in. These do not show up in HA at all. I have to un-hide them in the Plejd app and restart HA, _then_ they show up. Would be amazing if devices for these switches were created in HA and set to hidden there when they are hidden in Plejd.

Thanks for a great project!

**Comment by pierrei** [comment]
I had a look and this might be in the direction of what I'm thinking: https://github.com/thomasloven/hass-plejd/compare/master...pierrei:hass-plejd:pierrei/add-hidden-devices

**Comment by oyvindwe** [comment]
@pierrei I think you are on the right track with this change. Have you tested it out locally?

**Comment by thomasloven** [comment]
Looks good to me. Would you mind making a PR?

**Comment by pierrei** [comment]
I'll test it myself now and if all works well I'll create a PR 👍

**Comment by pierrei** [comment]
Yes, it's working well! The devices show up in the device list but the switches in this case are hidden "by integration". I'll create the PR!

Device:
<img width="1017" alt="Screenshot 2024-05-10 at 09 14 32" src="https://github.com/thomasloven/hass-plejd/assets/994715/f0d0c06a-3592-44ac-8e51-dbac3040ff31">

Individual switch settings:
<img width="562" alt="Screenshot 2024-05-10 at 09 14 48" src="https://github.com/thomasloven/hass-plejd/assets/994715/eaa0b0fc-a71d-4e5f-a0e2-c17293bd8926">

**Comment by pierrei** [comment]
https://github.com/thomasloven/hass-plejd/pull/65

**Comment by pierrei** [comment]
Is there anything we need to account for on updates btw? If the integration has been set up and devices created, if a user later hides something in Plejd should we also push an update to HA to update visibility? 🤔

**Comment by oyvindwe** [comment]
> Is there anything we need to account for on updates btw? If the integration has been set up and devices created, if a user later hides something in Plejd should we also push an update to HA to update visibility? 🤔

That is not supported by HA according to the documentation for `entity_registry_visible_default`:
> Return if the entity should be visible when first added.
>
> This only applies when fist added to the entity registry.

I think this is as good as it gets!

**Comment by thomasloven** [comment]
Closed by #65
