### ISSUE TITLE
Bluetooth questions

### ISSUE THREAD

**Issue by Sleepybear95** [thomasloven/hass-plejd#69]
HI. I just setup a Bluetooth Proxy on a ESP32 and added both the Addon and Integration in HAOS. Do I need the USB bluetooth dongle or can the ESP32 module be used instead? If so, How?

PS: New to Home Assistant so trying out stuff.

**Comment by thomasloven** [comment]
If you have an esp#" with bluetooth proxy installed and that is connected to your home assistant, you do not also need a bluetooth dongle.
