### ISSUE TITLE
Smooth dimming?

### ISSUE THREAD

**Issue by JacobWiqvist** [thomasloven/hass-plejd#85]
I don't know if this is possible or if it would overload blueooth, or if it is even technically possible. But currently, dimmers do not send their value continuously, but after you release the knob or slider in the app. This means that if you want to sync 2 lights of different brands, the new lighting value is not sent until the other has stopped. Then the lighting value jumps to the set value. If possible? Is it possible to fix a setting so that the value is sent more continuously, perhaps at least 100-300 millisecond intervals.

This would open the possibility for softer dimming and perhaps use Plejd as a volume control, for example. sonos.

As Plejd's own stuff does to each other.

Best regards Jacob W!

**Comment by thomasloven** [comment]
This is unfortunately not possible.
The plejd dimmer is bound directly to the device it controls via an encrypted connection, and does not send any information to the mesh. So the only thing that can be seen is the level reported by the light itself - which it only does after it has stabilized.

**Comment by JacobWiqvist** [comment]
Homekit have a smoot dimming with Plejd threw threw gateway. That means that at least the gateway can send a smooth signal to the dimmers? Is it possible to in some way use that?

**Comment by thomasloven** [comment]
> Homekit have a smoot dimming with Plejd threw threw gateway. That means that at least the gateway can send a smooth signal to the dimmers? Is it possible to in some way use that?

I bought a gateway just to be able to test this, but can't find any options for smooth dimming anywhere.
Could you please show me where?

**Comment by JacobWiqvist** [comment]
The soft dimming comes from homekit, that is, if you drag the slider in
homekit on your IOS device, which is connected to the Plejd Gateway that
can send a signal to plejd devices. The dimmer will act/behave quite
similarly to how it behaves when you drag your finger in the plejd app.

I don't think there is any special mode in the gateway that can do this.
But I think that since homekit can send a signal that follows the slider in
homekit, home assistant should be able to send a signal that follows the
slider.

It will be a hell of a detour for the signal.

HomeAssistant > Homekit slider > Plejd Gateway > Plejd Dimmer.

I guess it is an encrypted signal all the way from homekit to Plejd dimmer.

But the result is that it is possible to send a signal that follows the
finger in real time.

Den sön 5 jan. 2025 kl 17:23 skrev Thomas Lovén ***@***.***>:

**Comment by JacobWiqvist** [comment]
It might be possible to make a semi-soft signal by sending many signal
changes per second, maybe you know better?


Den sön 5 jan. 2025 kl 17:34 skrev Jacob Wiqvist ***@***.***>:

**Comment by thomasloven** [comment]
So you're saying you are NOT seeing this behavior from Home Assistant when using the plejd gateway through homekit, but only when using the homekit app on your phone?

**Comment by JacobWiqvist** [comment]
I think so! Unfortunately.

I have both a philips hue dial rotary switch that controls the volume to
sonos threw node red, that switch can smooth lower and increase the volume
on sonos by rotating it. But I think it is all done in the script in node
read.

sön 5 jan. 2025 kl. 17:37 skrev Thomas Lovén ***@***.***>:

**Comment by JacobWiqvist** [comment]
I use this on the toilet:
https://flows.nodered.org/flow/c95d562d4858cbe1bf80fee95ba9815f

Maybe that can give some inspiration!

Regards Jacob

sön 5 jan. 2025 kl. 17:42 skrev Jacob Wiqvist ***@***.***>:
